spring:
  application:
    name: web-security-emulator

  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/southwind
    username: root
    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
